#!/bin/bash                                                                                  
echo "Holberton School is so cool!"

#!/bin/bash                                                                                  echo "Holberton School is so cool!"                                                           


